# Generated by Django 5.1 on 2024-10-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='public',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
